### General Preprocessing

The EDA identified several preprocessing requirements before modeling. Most variables contained valid values, however, undocumented categories were observed in the EDUCATION and MARRIAGE variables. In addition, categorical variables required encoding before they could be used by machine learning algorithms. Because the target variable is binary, it also needed to be separated from the predictor variables.

In [263]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [264]:
df = pd.read_excel('../data/raw/default_of_credit_card_clients.xls', header=1)
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [265]:
df_prep = df.copy()

Renaming the column

In [266]:
df_prep = df_prep.rename(columns={'default payment next month':'DEFAULT'})
df_prep.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

Dropping ID column

In [267]:
df_prep = df_prep.drop(columns='ID')
df_prep.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,2,2,34,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,2,1,37,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

#### EDUCATION

In [268]:
edu_counts = df_prep['EDUCATION'].value_counts().sort_index()
edu_counts

EDUCATION
0       14
1    10585
2    14030
3     4917
4      123
5      280
6       51
Name: count, dtype: int64

In [269]:
df_prep['EDUCATION'] = df_prep['EDUCATION'].replace([0,5,6,], 4)

In [270]:
df_prep['EDUCATION'].value_counts().sort_index()

EDUCATION
1    10585
2    14030
3     4917
4      468
Name: count, dtype: int64

#### Marital Status

In [271]:
mar_counts = df_prep['MARRIAGE'].value_counts().sort_index()
mar_counts

MARRIAGE
0       54
1    13659
2    15964
3      323
Name: count, dtype: int64

In [272]:
df_prep['MARRIAGE'] = df_prep['MARRIAGE'].replace([0], 3)

In [273]:
df_prep['MARRIAGE'].value_counts().sort_index()

MARRIAGE
1    13659
2    15964
3      377
Name: count, dtype: int64

Dummies

In [274]:
df_prep = pd.get_dummies(df_prep, columns=['SEX', 'EDUCATION', 'MARRIAGE'], drop_first=True)

In [275]:
df_prep

,LIMIT_BAL,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,...,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT,SEX_2,EDUCATION_2,EDUCATION_3,EDUCATION_4,MARRIAGE_2,MARRIAGE_3
0,20000,24,2,2,-1,-1,-2,-2,3913,3102,...,0,0,0,1,True,True,False,False,False,False
1,120000,26,-1,2,0,0,0,2,2682,1725,...,1000,0,2000,1,True,True,False,False,True,False
2,90000,34,0,0,0,0,0,0,29239,14027,...,1000,1000,5000,0,True,True,False,False,True,False
3,50000,37,0,0,0,0,0,0,46990,48233,...,1100,1069,1000,0,True,True,False,False,False,False
4,50000,57,-1,0,-1,0,0,0,8617,5670,...,9000,689,679,0,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000,39,0,0,0,0,0,0,188948,192815,...,3047,5000,1000,0,False,False,True,False,False,False
29996,150000,43,-1,-1,-1,-1,0,0,1683,1828,...,129,0,0,0,False,False,True,False,True,False
29997,30000,37,4,3,2,-1,0,0,3565,3356,...,4200,2000,3100,1,False,True,False,False,True,False
29998,80000,41,1,-1,0,0,0,-1,-1645,78379,...,1926,52964,1804,1,False,False,True,False,False,False
29999,50000,46,0,0,0,0,0,0,47929,48905,...,1000,1000,1000,1,False,True,False,False,False,False

The categorical variables SEX, EDUCATION, and MARRIAGE were converted into binary indicator variables using one-hot encoding. The drop_first=True option was used to avoid multicollinearity by removing one reference category from each variable.

In [276]:
df_prep.to_csv('../data/processed/preprocessed_credit_default.csv', index=False)