### General Preprocessing

The EDA identified several preprocessing requirements before modeling. Most variables contained valid values, however, undocumented categories were observed in the EDUCATION and MARRIAGE variables. In addition, categorical variables required encoding before they could be used by machine learning algorithms. Because the target variable is binary, it also needed to be separated from the predictor variables.

In [230]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [231]:
df = pd.read_excel('../data/raw/default_of_credit_card_clients.xls', header=1)
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [232]:
df_prep = df.copy()

Renaming the column

In [233]:
df_prep = df_prep.rename(columns={'default payment next month':'DEFAULT'})
df_prep.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

Dropping ID column

In [234]:
df_prep = df_prep.drop(columns='ID')
df_prep.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,2,2,34,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,2,1,37,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

#### EDUCATION

In [235]:
edu_counts = df_prep['EDUCATION'].value_counts().sort_index()
edu_counts

EDUCATION
0       14
1    10585
2    14030
3     4917
4      123
5      280
6       51
Name: count, dtype: int64

In [236]:
df_prep['EDUCATION'] = df_prep['EDUCATION'].replace([0,5,6,], 4)

In [237]:
df_prep['EDUCATION'].value_counts().sort_index()

EDUCATION
1    10585
2    14030
3     4917
4      468
Name: count, dtype: int64

#### Marital Status

In [238]:
mar_counts = df_prep['MARRIAGE'].value_counts().sort_index()
mar_counts

MARRIAGE
0       54
1    13659
2    15964
3      323
Name: count, dtype: int64

In [239]:
df_prep['MARRIAGE'] = df_prep['MARRIAGE'].replace([0], 3)

In [240]:
df_prep['MARRIAGE'].value_counts().sort_index()

MARRIAGE
1    13659
2    15964
3      377
Name: count, dtype: int64

In [241]:
df_prep.to_csv('../data/processed/preprocessed_credit_default.csv', index=False)

### Preprocessing Continued

In [242]:
X = df_prep.drop(columns='DEFAULT')
y = df_prep['DEFAULT']

In [243]:
X.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,20000,2,2,1,24,2,2,-1,-1,-2,...,689,0,0,0,0,689,0,0,0,0
1,120000,2,2,2,26,-1,2,0,0,0,...,2682,3272,3455,3261,0,1000,1000,1000,0,2000
2,90000,2,2,2,34,0,0,0,0,0,...,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000
3,50000,2,2,1,37,0,0,0,0,0,...,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000
4,50000,1,2,1,57,-1,0,-1,0,0,...,35835,20940,19146,19131,2000,36681,10000,9000,689,679

In [244]:
y.head()

0    1
1    1
2    0
3    0
4    0
Name: DEFAULT, dtype: int64

The categorical variables SEX, EDUCATION, and MARRIAGE were converted into binary indicator variables using one-hot encoding. The drop_first=True option was used to avoid multicollinearity by removing one reference category from each variable.

In [245]:
X = pd.get_dummies(X, columns=['SEX', 'EDUCATION', 'MARRIAGE'], drop_first=True)

In [246]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   LIMIT_BAL    30000 non-null  int64
 1   AGE          30000 non-null  int64
 2   PAY_0        30000 non-null  int64
 3   PAY_2        30000 non-null  int64
 4   PAY_3        30000 non-null  int64
 5   PAY_4        30000 non-null  int64
 6   PAY_5        30000 non-null  int64
 7   PAY_6        30000 non-null  int64
 8   BILL_AMT1    30000 non-null  int64
 9   BILL_AMT2    30000 non-null  int64
 10  BILL_AMT3    30000 non-null  int64
 11  BILL_AMT4    30000 non-null  int64
 12  BILL_AMT5    30000 non-null  int64
 13  BILL_AMT6    30000 non-null  int64
 14  PAY_AMT1     30000 non-null  int64
 15  PAY_AMT2     30000 non-null  int64
 16  PAY_AMT3     30000 non-null  int64
 17  PAY_AMT4     30000 non-null  int64
 18  PAY_AMT5     30000 non-null  int64
 19  PAY_AMT6     30000 non-null  int64
 20  SEX_2        30000 non-null  bool
 21  EDUCATION_2  30000 non-null  bool
 22  EDUCATION_3  30000 non-null  bool
 23  EDUCATION_4  30000 non-null  bool
 24  MARRIAGE_2   30000 non-null  bool
 25  MARRIAGE_3   30000 non-null  bool
dtypes: bool(6), int64(20)
memory usage: 4.7 MB

Logistic regression is sensitive to variables measured on different scales. Therefore, continuous variables such as credit limit, age, bill amounts, and payment amounts were standardized, while categorical dummy variables and repayment status variables were left unchanged.

In [247]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [248]:
numeric_cols = [
    'LIMIT_BAL','AGE','BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5','BILL_AMT6','PAY_AMT1','PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6'
]

In [249]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [250]:
X.to_csv("../data/processed/X_preprocessed.csv", index=False)
y.to_csv("../data/processed/y_preprocessed.csv", index=False)